export const ignoredActions = [
  "bootstrap/fulfilled",
  "bootstrap/rejected",

  "auth/login/fulfilled",
  "auth/login/rejected",
  "auth/check/fulfilled",
  "auth/check/rejected",
  "auth/change/fulfilled",
  "auth/change/rejected",

  "users/create/fulfilled",
  "users/create/rejected",
  "users/getAll/fulfilled",
  "users/getAll/rejected",
  "users/remove/fulfilled",
  "users/remove/rejeceted",

  "f5/getAll/fulfilled",
  "f5/getAll/rejected",
  "f5/remove/all/fulfilled",
  "f5/remove/all/rejected",
  "f5/create/many/fulfilled",
  "f5/create/many/rejected",

  "node/getAll/fulfilled",
  "node/getAll/rejected",
  "node/remove/fulfilled",
  "node/remove/rejected",
  "node/update/fulfilled",
  "node/update/rejected",
  "node/remove/all/fulfilled",
  "node/remove/all/rejected",
  "node/create/many/fulfilled",
  "node/create/many/rejected",

  "interface/getAll/fulfilled",
  "interface/getAll/rejected",
  "interface/remove/fulfilled",
  "interface/remove/rejected",
  "interface/update/fulfilled",
  "interface/update/rejected",
  "interface/remove/all/fulfilled",
  "interface/remove/all/rejected",
  "interface/create/many/fulfilled",
  "interface/create/many/rejected",

  "error/getAll/fulfilled",
  "error/getAll/rejected",
  "error/remove/fulfilled",
  "error/remove/rejected",
  "error/update/fulfilled",
  "error/update/rejected",
  "error/remove/all/fulfilled",
  "error/remove/all/rejected",
  "error/create/many/fulfilled",
  "error/create/many/rejected",

  "alarm/getAll/fulfilled",
  "alarm/getAll/rejected",

  "data/getNodes/fulfilled",
  "data/getNodes/rejected",

  "data/getInterfaces/fulfilled",
  "data/getInterfaces/rejected",

  "settings/get/fulfilled",
  "settings/get/rejected",
  "settings/set/fulfilled",
  "settings/set/rejected",
];
